apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: abhishek626/k8s-react-app:latest  # Ensure this image is pushed to Docker Hub
          ports:
            - containerPort: 80